* File Format
:PROPERTIES:
:heading: 1
:END:
** hdf file (Hardware Definition File)
*** The source code for the hardware design
*** Describes the hardware architecture of an FPGA design, including the IP (Intellectual Property) cores, interconnections, and other hardware components. It is used as an input file for the FPGA design tool, such as Vivado, to synthesize, implement, and generate the bitstream file.
** bit file (Bitstream File)
*** Compiled binary representation of that design that can be loaded onto the FPGA
*** The configuration data for the FPGA
*** Is specified in the hdf file
** tcl file (Tool Command Language File)
*** Automate various tasks in tools like Xilinx Vivado, Cadence, and Synopsys
**** Configure and run a synthesis, place-and-route, or simulation process, or to define and execute custom flows and processes.
*
* Errors
:PROPERTIES:
:heading: 1
:END:
** Using switching or button as clock would appear an error
*** Error Prompt
**** [Place 30-574] Poor placement for routing between an IO pin and BUFG.
***** A routing issue between the input buffer ( ~IBUF~ ) of the clock ( ~CLK_IBUF~ ) and the global clock buffer ( ~BUFG~ ) in your design. The message is suggesting that the placement of the input buffer and the global clock buffer is sub-optimal and could cause routing congestion.
****** ~IBUF~: An interface between input signal and internal digital circuit
******* ~CLK_IBUF~: a special IBUF to receive clock signals
******** make sure the clock signal meets the requirement input specification
*** Reason
**** Vivado will automatically connect pins with clock event to clock input buffer
*** Debug
**** By adding this to .xdc file ~set_property CLOCK_DEDICATED_ROUTE FLASE [get_nets CLK_IBUF];~
***** set the clock dedicated route property to ~FALSE~ for the ~CLK_IBUF~ net
***** indicate that the clock signal should not be assigned to a dedicated routing resource on the device, such as a global clock network